server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index report_final_bilacare.html index.html index.htm;

    location / {
        try_files $uri $uri/ =404;
    }
}